# AzGovViz v6_major_20220521_1
# First things first:
# 1. Mandatory: define <Management Group Id> in line 11 (e.g. be992f89-5615-4745-baca-16e5d7b72a50)
# 2. Optional: enable the schedule (line 22,23)
# Documentation: https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting

name: AzGovViz_OIDC

env:
  OutputPath: wiki
  ManagementGroupId: 8619c67c-945a-48ae-8e77-35b1b71c9b98
  ScriptDir: pwsh #example: 'my folder\pwsh' or 'my folder/pwsh'
  ScriptPrereqFile: prerequisites.ps1
  ScriptFile: AzGovVizParallel.ps1
  #optional
  WebAppPublish: true #set to true and define the Web App details in the next 3 lines
  WebAppSubscriptionId: d4acc67e-26ec-4d83-8c11-14a434131193
  WebAppResourceGroup: Axpo-SandBox-NewHome-Documentation
  WebAppName: nhdoc

on:
  schedule:
  - cron:  '30 5 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#requirement OIDC
permissions:
  id-token: write
  contents: write

jobs:
  AzGovViz:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
       
      - name: Connect Azure OIDC
        uses: azure/login@v1
        with:
          client-id: ${{secrets.CLIENT_ID}} #create this secret
          tenant-id: ${{secrets.TENANT_ID}} #create this secret
          subscription-id: ${{secrets.SUBSCRIPTION_ID}} #create this secret
          enable-AzPSSession: true
      
      - name: Check prerequisites
        uses: azure/powershell@v1
        with:
          inlineScript: |
            . .\$($env:ScriptDir)\$($env:ScriptPrereqFile) -OutputPath ${env:OutputPath}
          azPSVersion: "latest"

      - name: Run AzGovViz
        uses: azure/powershell@v1
        with:
          inlineScript: |
            . .\$($env:ScriptDir)\$($env:ScriptFile) -ManagementGroupId ${env:ManagementGroupId} -SubscriptionId4AzContext ${{secrets.SUBSCRIPTION_ID}} -ScriptPath ${env:ScriptDir} -OutputPath ${env:OutputPath} -DoPSRule
          azPSVersion: "latest"
      
      - name: Push AzGovViz output to repository
        run: |        
          git config --global user.email "AzGovVizGHActions@ghActions.com"
          git config --global user.name "azgvz"
          git config pull.rebase false
          git add --all
          git commit -m "$GITHUB_WORKFLOW $GITHUB_JOB"
          git push

      - name: Publish HTML to WebApp
        if: env.WebAppPublish == 'true'
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $azAPICallConf = initAzAPICall -DebugAZAPICall $true
            $currentTask = "AzAPICall - Check if WebApp ($($env:WebAppName)) has Authentication enabled"
            $uri = "$($azAPICallConf['azAPIEndpointUrls'].ARM)/subscriptions/$($env:WebAppSubscriptionId)/resourceGroups/$($env:WebAppResourceGroup)/providers/Microsoft.Web/sites/$($env:WebAppName)/config/authsettings/list?api-version=2021-02-01"
            $method = 'POST'
            $request = AzAPICall -AzAPICallConfiguration $azAPICallConf -uri $uri -method $method -currentTask $currentTask -listenOn 'Content'

            $authStatus = $request.properties.enabled
            Write-Host "WebApp ($($env:WebAppName)) has Authentication enabled: $authStatus"
            if ($authStatus) {
                try {
                    Compress-Archive -Path "$($env:OutputPath)/AzGovViz_$($env:ManagementGroupId).html" -DestinationPath "$($env:OutputPath)/AzGovViz_$($env:ManagementGroupId).zip"
                    $null = Select-AzSubscription -SubscriptionId $($env:WebAppSubscriptionId)
                    if (Publish-AzWebApp -ResourceGroupName $($env:WebAppResourceGroup) -Name $($env:WebAppName) -ArchivePath "$($env:OutputPath)/AzGovViz_$($env:ManagementGroupId).zip" -Force) {
                        Write-Host "HTML published"
                    }
                }
                catch {
                    $_
                    Write-Host "HTML NOT published"
                    Write-Host "RBAC Role 'Website Contributor' is required"
                    exit 1
                }
            }
            else {
                Write-Host "Assuming and insisting that you do not want to publish your tenant insights to the public"
                Write-Host "HTML NOT published. Please configure authentication on the webApp ($($env:WebAppName))"
                exit 1
            }
          azPSVersion: "latest"