# AzGovViz v6_major_20220319_1
name: AzGovViz

env:
  OutputPath: wiki
  ManagementGroupId: <Management Group Id>
  ScriptDir: pwsh
  ScriptPrereqFile: prerequisites.ps1
  ScriptFile: AzGovVizParallel.ps1

on:
  #schedule:
  #  - cron:  '45 4,16 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  AzGovViz:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Connect Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.CREDS}}
          enable-AzPSSession: true 
          # CREDS looks like this:
          # {
          #   "tenantId": "<GUID>",
          #   "subscriptionId": "<GUID>",
          #   "clientId": "<GUID>",
          #   "clientSecret": "<GUID>"
          # }

      - name: Run AzGovViz
        uses: azure/powershell@v1
        with:
          inlineScript: |
            . .\$($env:ScriptDir)\$($env:ScriptPrereqFile)
            . .\$($env:ScriptDir)\$($env:ScriptFile) -ManagementGroupId ${env:ManagementGroupId} -ScriptPath ${env:ScriptDir} -OutputPath ${env:OutputPath}
          azPSVersion: "latest"
      
      - name: Push AzGovViz output to repository
        run: |        
          git config --global user.email "AzGovVizGHActions@ghActions.com"
          git config --global user.name "$GITHUB_ACTOR"
          git config pull.rebase false
          git add --all
          git commit -m "$GITHUB_WORKFLOW $GITHUB_JOB"
          git push